version: '3.8'

services:
  django_gunicorn:
    env_file:
      - .env
    build:
      context: .
      network: host
    container_name: django
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/mysite
    depends_on:
      - pg_db

  pg_db:
    container_name: pg_db
    environment:
      - POSTGRES_PASSWORD=django
      - POSTGRES_USER=django_user
      - POSTGRES_DB=Django_ac
    image: postgres:14.3-alpine
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    volumes:
      - ./mysite/school/static:/static
      - /etc/ssl:/etc/ssl
    ports:
      - "80:80"
      - "443:443"
    links:
      - django_gunicorn
    restart:
      always
    depends_on:
      - django_gunicorn

volumes:
  pgdbdata: null
  static:
      


