# Generated by Django 4.0.5 on 2022-07-02 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=30)),
                ('technincs', models.CharField(max_length=50)),
                ('tecNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technincs', models.CharField(max_length=50)),
                ('tecNumber', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=30)),
                ('accounting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.accounting')),
            ],
        ),
        migrations.AddField(
            model_name='accounting',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.store'),
        ),
    ]
