# Generated by Django 4.0.5 on 2022-07-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_accounting_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=30, verbose_name='Должность')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AlterField(
            model_name='adress',
            name='adress',
            field=models.CharField(max_length=50, verbose_name='Адресс'),
        ),
    ]
