# Generated by Django 4.0.5 on 2022-07-03 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounting',
            options={'verbose_name': 'Учётная книга', 'verbose_name_plural': 'Учётная книга'},
        ),
        migrations.AlterModelOptions(
            name='adress',
            options={'verbose_name': 'Здание', 'verbose_name_plural': 'Здания'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склад'},
        ),
        migrations.AlterField(
            model_name='accounting',
            name='store',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='school.store'),
        ),
    ]
