# Generated by Django 4.1.3 on 2023-04-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_rename_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='time',
            field=models.CharField(default='00.00.0000', max_length=50),
        ),
    ]
