# Generated by Django 4.1.3 on 2023-04-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_store_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='tecNumber',
            field=models.CharField(max_length=50),
        ),
    ]
