# Generated by Django 4.0.5 on 2022-10-13 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_castomer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='castomer',
            options={'verbose_name': 'Авторизация', 'verbose_name_plural': 'Авторизация'},
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='store',
        ),
        migrations.RemoveField(
            model_name='adress',
            name='accounting',
        ),
    ]
