# Generated by Django 4.2 on 2023-11-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_svt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svt',
            name='data_get',
            field=models.CharField(default='00.00.0000', max_length=500),
        ),
        migrations.AlterField(
            model_name='svt',
            name='data_inp',
            field=models.CharField(default='00.00.0000', max_length=500),
        ),
    ]
