# Generated by Django 4.2.7 on 2023-11-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_svt_data_get_alter_svt_data_inp'),
    ]

    operations = [
        migrations.AddField(
            model_name='svt',
            name='ser_number',
            field=models.CharField(default='00000000000', max_length=500),
        ),
    ]
