# Generated by Django 4.2.7 on 2023-11-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_svt_ser_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcountingBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('acounting', models.CharField(max_length=100)),
                ('inv_number', models.CharField(max_length=50)),
                ('ser_number', models.CharField(default='00000000000', max_length=500)),
                ('kab', models.CharField(default=0, max_length=5000)),
                ('quantity', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Учётная книга',
                'verbose_name_plural': 'Учётная книга',
            },
        ),
    ]
