# Generated by Django 4.2.7 on 2023-11-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_acountingbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='acountingbook',
            name='cmo',
            field=models.CharField(default='...', max_length=5000),
        ),
    ]
